name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Traer el código del repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Ejecutar pruebas unitarias
      - name: Run tests
        run: npm test

      # 5️⃣ Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Construir la imagen Docker con nombre completo del repo
      - name: Build Docker image
        run: docker build -t cangreburger/hola-mundo:latest .

      # 7️⃣ Subir la imagen a Docker Hub con nombre completo del repo
      - name: Push Docker image
        run: docker push cangreburger/hola-mundo:latest

      # 8️⃣ Deploy a Render
      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          https://api.render.com/deploy/srv-d2l545buibrs73est8f0
